### ISSUE TITLE
Simulation data structure

### ISSUE THREAD

**Issue by cfuselli** [acolijn/OptoSim#7]
The way the simulations files are structured are extremely inefficient for loading large amount of data. 
Restructuring is necessary to speed up. 

Also need to change filenames extensions to hdf5 instead of hd5f. 

Would also be better to have logs and models divided per run_id in the data folder.

**Comment by acolijn** [comment]
agreed. you can also specifiy a new data structure in the settings.ini. We will need to make changes to all routines that read the MC before using it.

**Comment by cfuselli** [comment]
Somehow solved with cee353c by @acolijn that kindly agreed to apply his future changes through nice and well documented pull requests :)
